version: '3.3'

services:
    webapp-server:
      build:
        context: .
        dockerfile: Dockerfile
      image: robots-server-img
      container_name: myapp-node-express-robots
      volumes:
       - .:/usr/src/app
       - /usr/src/app/node_modules
      ports:
        - "5000:5000"
      depends_on:
        - mongo
      env_file: .env
      environment:
        - MONGO_HOSTNAME=$MONGO_HOSTNAME
        - MONGO_PORT=$MONGO_PORT
        - MONGO_DB=$MONGO_DB
    mongo:
      image: mongo
      container_name: myapp-mongodb-robots
      ports:
        - "27017:27017"